development:
  providers_expire_in: 60.seconds
  consumer_key: '9cnkiWf4XmzNVQZTEem1rJv0odSMYYikNQBuCzqsHWnMget3txlnfKpQw1QlEOxat7zbHPJoDXZHJCMFTUoRxcnyQ0YrazzL9ZwWAmezFMRkSVQ7JwRAovaa'
  consumer_secret:  'KBUxy8vlBCej6VxpcJOb4PlmDN4U94O5cEYUJcpm6kqdhMiaiWMHFzu3wHvixE2jnRhoyfkr7mDBiORTn2GuCtF3YX38SN7AiQTKaUxcEwQ5kVrmSBtCdMuL'
  portal_token: 'KBUxy8vlBCej6VxpcJOb4PlmDN4U94O5cEYUJcpm6kqdhMiaiWMHFzu3wHvixE2jnRhoyfkr7mDBiORTn2GuCtF3YX38SN7AiQTKaUxcEwQ5kVrmSBtCdMuM'
  portal_secret: '9cnkiWf4XmzNVQZTEem1rJv0odSMYYikNQBuCzqsHWnMget3txlnfKpQw1QlEOxat7zbHPJoDXZHJCMFTUoRxcnyQ0YrazzL9ZwWAmezFMRkSVQ7JwRAovab'

test:
  consumer_key: '9cnkiWf4XmzNVQZTEem1rJv0odSMYYikNQBuCzqsHWnMget3txlnfKpQw1QlEOxat7zbHPJoDXZHJCMFTUoRxcnyQ0YrazzL9ZwWAmezFMRkSVQ7JwRAovaa'
  consumer_secret:  'KBUxy8vlBCej6VxpcJOb4PlmDN4U94O5cEYUJcpm6kqdhMiaiWMHFzu3wHvixE2jnRhoyfkr7mDBiORTn2GuCtF3YX38SN7AiQTKaUxcEwQ5kVrmSBtCdMuL'
  portal_token: 'KBUxy8vlBCej6VxpcJOb4PlmDN4U94O5cEYUJcpm6kqdhMiaiWMHFzu3wHvixE2jnRhoyfkr7mDBiORTn2GuCtF3YX38SN7AiQTKaUxcEwQ5kVrmSBtCdMuM'
  portal_secret: '9cnkiWf4XmzNVQZTEem1rJv0odSMYYikNQBuCzqsHWnMget3txlnfKpQw1QlEOxat7zbHPJoDXZHJCMFTUoRxcnyQ0YrazzL9ZwWAmezFMRkSVQ7JwRAovab'

production:
  consumer_key: '9cnkiWf4XmzNVQZTEem1rJv0odSMYYikNQBuCzqsHWnMget3txlnfKpQw1QlEOxat7zbHPJoDXZHJCMFTUoRxcnyQ0YrazzL9ZwWAmezFMRkSVQ7JwRAovaa'
  consumer_secret:  'KBUxy8vlBCej6VxpcJOb4PlmDN4U94O5cEYUJcpm6kqdhMiaiWMHFzu3wHvixE2jnRhoyfkr7mDBiORTn2GuCtF3YX38SN7AiQTKaUxcEwQ5kVrmSBtCdMuL'
  portal_token: 'KBUxy8vlBCej6VxpcJOb4PlmDN4U94O5cEYUJcpm6kqdhMiaiWMHFzu3wHvixE2jnRhoyfkr7mDBiORTn2GuCtF3YX38SN7AiQTKaUxcEwQ5kVrmSBtCdMuM'
  portal_secret: '9cnkiWf4XmzNVQZTEem1rJv0odSMYYikNQBuCzqsHWnMget3txlnfKpQw1QlEOxat7zbHPJoDXZHJCMFTUoRxcnyQ0YrazzL9ZwWAmezFMRkSVQ7JwRAovab'
